name: CI
on: [push]
  # push:
    # branches:
      # - 3.2.x
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    name: '${{ matrix.os.name}} | Java ${{ matrix.java.version}}'
    runs-on: ${{ matrix.os.id }}
    # if: ${{ github.repository == 'spring-projects/spring-boot' }}
    strategy:
      matrix:
        os:
          - id: ubuntu-22.04
            name: Linux
          - id: windows-latest
            name: Windows
        java:
          - version: 17
            toolchain: false
          - version: 21
            toolchain: true
          - version: 22
            toolchain: true
        exclude:
          - os:
              name: Linux
            java:
              version: 17
    steps:
      - name: Prepare Windows runner
        if: ${{ runner.os == 'Windows' }}
        run: |
          git config --global core.autocrlf true
          git config --global core.longPaths true
          Stop-Service -name Docker
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java.version }}
          java-toolchain: ${{ matrix.java.toolchain }}
          gradle-enterprise-secret-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
          gradle-enterprise-cache-user: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
          gradle-enterprise-cache-password: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      - name: Upload JAR Artifacts # <--- NEW STEP STARTS HERE
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.name}}-java-${{ matrix.java.version}}-jars # Name for your artifact (e.g., Linux-java-21-jars)
          path: |
            build/libs/*.jar # Path to your JAR files (adjust as needed for Maven or multiple JARs)
            target/*.jar # Add if you're using Maven, for example
          retention-days: 7 # Optional: How long to keep the artifact (default is 90 days, max 90)
          if-no-files-found: warn # Optional: What to do if no files match (warn, error, ignore)

      # - name: Send Notification
      #   uses: ./.github/actions/send-notification
      #   if: always()
      #   with:
      #     webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      #     status: ${{ job.status }}
      #     build-scan-url: ${{ steps.build.outputs.build-scan-url }}
      #     run-name: ${{ format('{0} | {1} | Java {2}', github.ref_name, matrix.os.name, matrix.java.version) }}
